"""
inertia/relatorios/exportador.py
Exporta resultados da sessão em JSON, CSV, HTML e TXT.

Cada formato tem sua própria função privada (_para_json, etc.)
e todas são acessadas via a função pública exportar_sessao().
"""
from __future__ import annotations

import csv
import io
import json
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import BaseLoader, Environment

from inertia.nucleo.modelos import SessaoScan

# ─── Template HTML ────────────────────────────────────────────────────────────

_TEMPLATE_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Inertia — {{ alvo }}</title>
  <style>
    :root{--bg:#0d1117;--s:#161b22;--b:#21262d;--c:#60a5fa;--g:#3fb950;
          --y:#e3b341;--r:#f85149;--dim:#8b949e;--w:#e6edf3;
          --font:'Courier New',monospace}
    *{box-sizing:border-box;margin:0;padding:0}
    body{background:var(--bg);color:var(--w);font-family:var(--font);padding:2rem}
    header{border-bottom:2px solid var(--c);padding-bottom:1rem;margin-bottom:2rem}
    h1{color:var(--c);font-size:1.8rem;letter-spacing:3px}
    .meta{color:var(--dim);margin-top:.4rem;font-size:.85rem}
    .stats{display:flex;gap:1.5rem;margin:1.5rem 0;flex-wrap:wrap}
    .stat .v{font-size:1.8rem;font-weight:bold}
    .stat .l{font-size:.72rem;color:var(--dim);text-transform:uppercase;letter-spacing:1px}
    .c{color:var(--c)}.g{color:var(--g)}.y{color:var(--y)}.dim{color:var(--dim)}
    table{width:100%;border-collapse:collapse;font-size:.88rem}
    th{color:var(--dim);font-size:.72rem;text-transform:uppercase;letter-spacing:1px;
       padding:.6rem 1rem;border-bottom:2px solid var(--b);text-align:left;font-weight:normal}
    td{padding:.5rem 1rem;border-bottom:1px solid var(--b)}
    tr:hover{background:rgba(96,165,250,.04)}
    .open{color:var(--g);font-weight:bold}
    .banner{color:var(--g);opacity:.6;font-style:italic}
    .cpe{color:var(--dim);font-size:.8rem}
    footer{margin-top:2rem;color:var(--dim);font-size:.75rem;
           border-top:1px solid var(--b);padding-top:1rem}
  </style>
</head>
<body>
<header>
  <h1>INERTIA</h1>
  <div class="meta">
    Target: <strong class="c">{{ alvo }}</strong> &nbsp;·&nbsp;
    IP: <strong class="c">{{ ip }}</strong> &nbsp;·&nbsp;
    {{ gerado_em }}
  </div>
</header>
<div class="stats">
  <div class="stat"><div class="v c">{{ stats.total }}</div><div class="l">Ports Scanned</div></div>
  <div class="stat"><div class="v g">{{ stats.abertas }}</div><div class="l">Open</div></div>
  <div class="stat"><div class="v dim">{{ stats.fechadas }}</div><div class="l">Closed</div></div>
  <div class="stat"><div class="v y">{{ stats.filtradas }}</div><div class="l">Filtered</div></div>
  <div class="stat"><div class="v c">{{ "%.2f"|format(stats.duracao_s) }}s</div><div class="l">Duration</div></div>
  <div class="stat"><div class="v dim">{{ "%.0f"|format(stats.taxa) }} p/s</div><div class="l">Rate</div></div>
</div>
<table>
  <thead><tr>
    <th>Port</th><th>Proto</th><th>State</th>
    <th>Service</th><th>Latency</th><th>CPE</th><th>Banner</th>
  </tr></thead>
  <tbody>
  {% for r in portas %}
  <tr>
    <td><strong>{{ r.porta }}</strong></td>
    <td class="dim">{{ r.protocolo }}</td>
    <td class="open">● {{ r.status }}</td>
    <td>{{ r.servico or "—" }}</td>
    <td class="y">{{ "%.1f"|format(r.latencia_ms) }} ms</td>
    <td class="cpe">{{ r.cpe or "—" }}</td>
    <td class="banner">{{ r.banner[:50] if r.banner else "—" }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
<footer>Generated by Inertia v1.0.0 — authorized use only.</footer>
</body></html>"""


# ─── Funções de serialização ──────────────────────────────────────────────────

def _para_json(sessao: SessaoScan) -> str:
    dados = {
        "inertia_version": "1.0.0",
        "scan_time":       datetime.now(timezone.utc).astimezone().isoformat(),
        "target": {
            "host":        sessao.alvo.host,
            "ip":          sessao.alvo.ip_resolvido,
            "reverse_dns": sessao.alvo.rdns,
        },
        "stats": {
            "elapsed_s":     round(sessao.tempo_decorrido_s, 3),
            "ports_scanned": sessao.total_portas,
            "scan_rate_pps": round(sessao.taxa_scan, 1),
            "concurrency":   sessao.concorrencia,
            "timeout_s":     sessao.timeout_s,
        },
        "open_ports": [
            {
                "port":       r.porta,
                "protocol":   r.protocolo,
                "state":      r.status,
                "service":    r.servico,
                "latency_ms": r.latencia_ms,
                "banner":     r.banner,
                "cpe":        r.cpe,
            }
            for r in sessao.portas_abertas
        ],
    }
    return json.dumps(dados, indent=2, ensure_ascii=False)


def _para_csv(sessao: SessaoScan) -> str:
    buf     = io.StringIO()
    escritor = csv.writer(buf)
    escritor.writerow(["port", "protocol", "state", "service", "latency_ms", "banner", "cpe"])
    for r in sessao.portas_abertas:
        escritor.writerow([
            r.porta, r.protocolo, r.status,
            r.servico, r.latencia_ms, r.banner, r.cpe,
        ])
    return buf.getvalue()


def _para_html(sessao: SessaoScan) -> str:
    stats = {
        "total":     sessao.total_portas,
        "abertas":   len(sessao.portas_abertas),
        "fechadas":  sum(1 for r in sessao.resultados if r.status == "closed"),
        "filtradas": sum(1 for r in sessao.resultados if r.status == "filtered"),
        "duracao_s": sessao.tempo_decorrido_s,
        "taxa":      sessao.taxa_scan,
    }
    template = Environment(loader=BaseLoader()).from_string(_TEMPLATE_HTML)
    return template.render(
        alvo      = sessao.alvo.host,
        ip        = sessao.alvo.ip_resolvido,
        gerado_em = datetime.now(timezone.utc).astimezone().strftime("%Y-%m-%d %H:%M:%S %Z"),
        stats     = stats,
        portas    = sessao.portas_abertas,
    )


def _para_txt(sessao: SessaoScan) -> str:
    linhas = [
        "INERTIA Port Scan Report",
        f"Generated : {datetime.now(timezone.utc).astimezone().strftime('%Y-%m-%d %H:%M:%S %Z')}",
        f"Target    : {sessao.alvo.host} ({sessao.alvo.ip_resolvido})",
        f"Elapsed   : {sessao.tempo_decorrido_s:.2f}s  |  "
        f"{sessao.total_portas} ports  |  {sessao.taxa_scan:.0f} pps",
        "",
        f"{'PORT':<8} {'PROTO':<6} {'STATE':<10} {'SERVICE':<14} {'LATENCY':>10}  BANNER",
        "─" * 90,
    ]
    for r in sessao.portas_abertas:
        banner = (r.banner or "")[:40].replace("\n", " ")
        linhas.append(
            f"{r.porta:<8} {r.protocolo:<6} {r.status:<10} "
            f"{(r.servico or '—'):<14} {r.latencia_ms:>8.1f}ms  {banner}"
        )
    return "\n".join(linhas) + "\n"


# ─── Mapeamento de formatos ───────────────────────────────────────────────────

_FORMATOS: dict[str, callable] = {
    "json": _para_json,
    "csv":  _para_csv,
    "html": _para_html,
    "txt":  _para_txt,
}

FORMATOS_SUPORTADOS = list(_FORMATOS.keys())


# ─── API pública ──────────────────────────────────────────────────────────────

def exportar_sessao(sessao: SessaoScan, caminho: str, formato: str) -> Path:
    """
    Exporta os resultados da sessão para um arquivo.

    Parâmetros:
      sessao  — sessão de varredura com resultados
      caminho — caminho do arquivo de saída
      formato — "json", "csv", "html" ou "txt"

    Retorna o Path do arquivo criado.
    Lança ValueError para formato desconhecido.
    """
    formato = formato.lower().strip(".")

    if formato not in _FORMATOS:
        raise ValueError(
            f"Formato '{formato}' desconhecido. "
            f"Suportados: {', '.join(FORMATOS_SUPORTADOS)}"
        )

    destino = Path(caminho)
    if destino.is_dir():
        raise ValueError(f"'{caminho}' é um diretório, não um arquivo")

    destino.parent.mkdir(parents=True, exist_ok=True)
    destino.write_text(_FORMATOS[formato](sessao), encoding="utf-8")

    return destino
